URL = "https://www.airhaifa.com/"
FIRST_NAME = "QA"
LAST_NAME = "Test"
PAX_TITLE_OPTIONS = ["Mr.", "Mrs.", "Ms."]
PHONE_NUMBER = "522484950"
EMAIL = "qa@go7.io"
DOB_DATE_FILED = (1,28)
DOB_MONTH_FILED = (1, 12)
DOB_YEAR_FILED = (1950, 2000)
